image: zen9073/play:1.4.2

stages:
  - init
  - test

before_script:
  - export JAVA_HOME=/opt/jdk1.8.0_112
  - export CLASSPATH=.:$JAVA_HOME/lib
  - export PATH=.:$JAVA_HOME/bin:$PATH
  - export PLAY_HOME=/opt/play-1.4.2
  - export PATH=.:$PLAY_HOME:$PATH


cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
  
job0:
  stage: init
  script:
    - cd core
    - play dependencies  --sync
    - pwd
  tags:
    - efk
  only:
    - master
    
job1:
  stage: test
  script:
    - cd core
    - pwd
    - ls
    - java -jar lib/checkStyle-8.1.jar -c conf/Erp_checkStyle.xml app -e app/views
  tags:
    - efk
  only:
    - master


