
package com.amazonservices.mws.FulfillmentInboundShipment._2010_10_01.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AddressLine2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DistrictOrCounty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StateOrProvinceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Oct 22 09:48:20 UTC 2010
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", propOrder = {
    "name",
    "addressLine1",
    "addressLine2",
    "districtOrCounty",
    "city",
    "stateOrProvinceCode",
    "countryCode",
    "postalCode"
})
public class Address {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "AddressLine1", required = true)
    protected String addressLine1;
    @XmlElement(name = "AddressLine2")
    protected String addressLine2;
    @XmlElement(name = "DistrictOrCounty")
    protected String districtOrCounty;
    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "StateOrProvinceCode", required = true)
    protected String stateOrProvinceCode;
    @XmlElement(name = "CountryCode", required = true)
    protected String countryCode;
    @XmlElement(name = "PostalCode")
    protected String postalCode;

    /**
     * Default constructor
     * 
     */
    public Address() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public Address(final String name, final String addressLine1, final String addressLine2, final String districtOrCounty, final String city, final String stateOrProvinceCode, final String countryCode, final String postalCode) {
        this.name = name;
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.districtOrCounty = districtOrCounty;
        this.city = city;
        this.stateOrProvinceCode = stateOrProvinceCode;
        this.countryCode = countryCode;
        this.postalCode = postalCode;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine1(String value) {
        this.addressLine1 = value;
    }

    public boolean isSetAddressLine1() {
        return (this.addressLine1 != null);
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine2(String value) {
        this.addressLine2 = value;
    }

    public boolean isSetAddressLine2() {
        return (this.addressLine2 != null);
    }

    /**
     * Gets the value of the districtOrCounty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrictOrCounty() {
        return districtOrCounty;
    }

    /**
     * Sets the value of the districtOrCounty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrictOrCounty(String value) {
        this.districtOrCounty = value;
    }

    public boolean isSetDistrictOrCounty() {
        return (this.districtOrCounty!= null);
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    public boolean isSetCity() {
        return (this.city!= null);
    }

    /**
     * Gets the value of the stateOrProvinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateOrProvinceCode() {
        return stateOrProvinceCode;
    }

    /**
     * Sets the value of the stateOrProvinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateOrProvinceCode(String value) {
        this.stateOrProvinceCode = value;
    }

    public boolean isSetStateOrProvinceCode() {
        return (this.stateOrProvinceCode!= null);
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    public boolean isSetCountryCode() {
        return (this.countryCode!= null);
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    public boolean isSetPostalCode() {
        return (this.postalCode!= null);
    }

    /**
     * Sets the value of the Name property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Address withName(String value) {
        setName(value);
        return this;
    }

    /**
     * Sets the value of the AddressLine1 property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Address withAddressLine1(String value) {
        setAddressLine1(value);
        return this;
    }

    /**
     * Sets the value of the AddressLine2 property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Address withAddressLine2(String value) {
        setAddressLine2(value);
        return this;
    }

    /**
     * Sets the value of the DistrictOrCounty property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Address withDistrictOrCounty(String value) {
        setDistrictOrCounty(value);
        return this;
    }

    /**
     * Sets the value of the City property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Address withCity(String value) {
        setCity(value);
        return this;
    }

    /**
     * Sets the value of the StateOrProvinceCode property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Address withStateOrProvinceCode(String value) {
        setStateOrProvinceCode(value);
        return this;
    }

    /**
     * Sets the value of the CountryCode property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Address withCountryCode(String value) {
        setCountryCode(value);
        return this;
    }

    /**
     * Sets the value of the PostalCode property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Address withPostalCode(String value) {
        setPostalCode(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetName()) {
            xml.append("<Name>");
            xml.append(escapeXML(getName()));
            xml.append("</Name>");
        }
        if (isSetAddressLine1()) {
            xml.append("<AddressLine1>");
            xml.append(escapeXML(getAddressLine1()));
            xml.append("</AddressLine1>");
        }
        if (isSetAddressLine2()) {
            xml.append("<AddressLine2>");
            xml.append(escapeXML(getAddressLine2()));
            xml.append("</AddressLine2>");
        }
        if (isSetDistrictOrCounty()) {
            xml.append("<DistrictOrCounty>");
            xml.append(escapeXML(getDistrictOrCounty()));
            xml.append("</DistrictOrCounty>");
        }
        if (isSetCity()) {
            xml.append("<City>");
            xml.append(escapeXML(getCity()));
            xml.append("</City>");
        }
        if (isSetStateOrProvinceCode()) {
            xml.append("<StateOrProvinceCode>");
            xml.append(escapeXML(getStateOrProvinceCode()));
            xml.append("</StateOrProvinceCode>");
        }
        if (isSetCountryCode()) {
            xml.append("<CountryCode>");
            xml.append(escapeXML(getCountryCode()));
            xml.append("</CountryCode>");
        }
        if (isSetPostalCode()) {
            xml.append("<PostalCode>");
            xml.append(escapeXML(getPostalCode()));
            xml.append("</PostalCode>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetName()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Name"));
            json.append(" : ");
            json.append(quoteJSON(getName()));
            first = false;
        }
        if (isSetAddressLine1()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("AddressLine1"));
            json.append(" : ");
            json.append(quoteJSON(getAddressLine1()));
            first = false;
        }
        if (isSetAddressLine2()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("AddressLine2"));
            json.append(" : ");
            json.append(quoteJSON(getAddressLine2()));
            first = false;
        }
        if (isSetDistrictOrCounty()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("DistrictOrCounty"));
            json.append(" : ");
            json.append(quoteJSON(getDistrictOrCounty()));
            first = false;
        }
        if (isSetCity()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("City"));
            json.append(" : ");
            json.append(quoteJSON(getCity()));
            first = false;
        }
        if (isSetStateOrProvinceCode()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("StateOrProvinceCode"));
            json.append(" : ");
            json.append(quoteJSON(getStateOrProvinceCode()));
            first = false;
        }
        if (isSetCountryCode()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CountryCode"));
            json.append(" : ");
            json.append(quoteJSON(getCountryCode()));
            first = false;
        }
        if (isSetPostalCode()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("PostalCode"));
            json.append(" : ");
            json.append(quoteJSON(getPostalCode()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
