
package com.amazonservices.mws.FulfillmentInboundShipment._2010_10_01.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InboundShipmentPlans" type="{http://mws.amazonaws.com/FulfillmentInboundShipment/2010-10-01/}InboundShipmentPlanList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Oct 22 09:48:20 UTC 2010
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inboundShipmentPlans"
})
@XmlRootElement(name = "CreateInboundShipmentPlanResult")
public class CreateInboundShipmentPlanResult {

    @XmlElement(name = "InboundShipmentPlans")
    protected InboundShipmentPlanList inboundShipmentPlans;

    /**
     * Default constructor
     * 
     */
    public CreateInboundShipmentPlanResult() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public CreateInboundShipmentPlanResult(final InboundShipmentPlanList inboundShipmentPlans) {
        this.inboundShipmentPlans = inboundShipmentPlans;
    }

    /**
     * Gets the value of the inboundShipmentPlans property.
     * 
     * @return
     *     possible object is
     *     {@link InboundShipmentPlanList }
     *     
     */
    public InboundShipmentPlanList getInboundShipmentPlans() {
        return inboundShipmentPlans;
    }

    /**
     * Sets the value of the inboundShipmentPlans property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundShipmentPlanList }
     *     
     */
    public void setInboundShipmentPlans(InboundShipmentPlanList value) {
        this.inboundShipmentPlans = value;
    }

    public boolean isSetInboundShipmentPlans() {
        return (this.inboundShipmentPlans!= null);
    }

    /**
     * Sets the value of the InboundShipmentPlans property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public CreateInboundShipmentPlanResult withInboundShipmentPlans(InboundShipmentPlanList value) {
        setInboundShipmentPlans(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetInboundShipmentPlans()) {
            InboundShipmentPlanList  inboundShipmentPlans = getInboundShipmentPlans();
            xml.append("<InboundShipmentPlans>");
            xml.append(inboundShipmentPlans.toXMLFragment());
            xml.append("</InboundShipmentPlans>");
        } 
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetInboundShipmentPlans()) {
            if (!first) json.append(", ");
            json.append("\"InboundShipmentPlans\" : {");
            InboundShipmentPlanList  inboundShipmentPlans = getInboundShipmentPlans();


            json.append(inboundShipmentPlans.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
