
package com.amazonservices.mws.FulfillmentInboundShipment._2010_10_01.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InboundShipmentItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InboundShipmentItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShipmentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SellerSKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FulfillmentNetworkSKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QuantityShipped" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="QuantityReceived" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Oct 22 09:48:20 UTC 2010
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InboundShipmentItem", propOrder = {
    "shipmentId",
    "sellerSKU",
    "fulfillmentNetworkSKU",
    "quantityShipped",
    "quantityReceived"
})
public class InboundShipmentItem {

    @XmlElement(name = "ShipmentId")
    protected String shipmentId;
    @XmlElement(name = "SellerSKU", required = true)
    protected String sellerSKU;
    @XmlElement(name = "FulfillmentNetworkSKU")
    protected String fulfillmentNetworkSKU;
    @XmlElement(name = "QuantityShipped")
    protected int quantityShipped;
    @XmlElement(name = "QuantityReceived")
    protected Integer quantityReceived;

    /**
     * Default constructor
     * 
     */
    public InboundShipmentItem() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public InboundShipmentItem(final String shipmentId, final String sellerSKU, final String fulfillmentNetworkSKU, final int quantityShipped, final Integer quantityReceived) {
        this.shipmentId = shipmentId;
        this.sellerSKU = sellerSKU;
        this.fulfillmentNetworkSKU = fulfillmentNetworkSKU;
        this.quantityShipped = quantityShipped;
        this.quantityReceived = quantityReceived;
    }

    /**
     * Gets the value of the shipmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentId() {
        return shipmentId;
    }

    /**
     * Sets the value of the shipmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentId(String value) {
        this.shipmentId = value;
    }

    public boolean isSetShipmentId() {
        return (this.shipmentId!= null);
    }

    /**
     * Gets the value of the sellerSKU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerSKU() {
        return sellerSKU;
    }

    /**
     * Sets the value of the sellerSKU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerSKU(String value) {
        this.sellerSKU = value;
    }

    public boolean isSetSellerSKU() {
        return (this.sellerSKU!= null);
    }

    /**
     * Gets the value of the fulfillmentNetworkSKU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillmentNetworkSKU() {
        return fulfillmentNetworkSKU;
    }

    /**
     * Sets the value of the fulfillmentNetworkSKU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillmentNetworkSKU(String value) {
        this.fulfillmentNetworkSKU = value;
    }

    public boolean isSetFulfillmentNetworkSKU() {
        return (this.fulfillmentNetworkSKU!= null);
    }

    /**
     * Gets the value of the quantityShipped property.
     * 
     */
    public int getQuantityShipped() {
        return quantityShipped;
    }

    /**
     * Sets the value of the quantityShipped property.
     * 
     */
    public void setQuantityShipped(int value) {
        this.quantityShipped = value;
    }

    public boolean isSetQuantityShipped() {
        return true;
    }

    /**
     * Gets the value of the quantityReceived property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQuantityReceived() {
        return quantityReceived;
    }

    /**
     * Sets the value of the quantityReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQuantityReceived(Integer value) {
        this.quantityReceived = value;
    }

    public boolean isSetQuantityReceived() {
        return (this.quantityReceived!= null);
    }

    /**
     * Sets the value of the ShipmentId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InboundShipmentItem withShipmentId(String value) {
        setShipmentId(value);
        return this;
    }

    /**
     * Sets the value of the SellerSKU property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InboundShipmentItem withSellerSKU(String value) {
        setSellerSKU(value);
        return this;
    }

    /**
     * Sets the value of the FulfillmentNetworkSKU property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InboundShipmentItem withFulfillmentNetworkSKU(String value) {
        setFulfillmentNetworkSKU(value);
        return this;
    }

    /**
     * Sets the value of the QuantityShipped property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InboundShipmentItem withQuantityShipped(int value) {
        setQuantityShipped(value);
        return this;
    }

    /**
     * Sets the value of the QuantityReceived property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InboundShipmentItem withQuantityReceived(Integer value) {
        setQuantityReceived(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetShipmentId()) {
            xml.append("<ShipmentId>");
            xml.append(escapeXML(getShipmentId()));
            xml.append("</ShipmentId>");
        }
        if (isSetSellerSKU()) {
            xml.append("<SellerSKU>");
            xml.append(escapeXML(getSellerSKU()));
            xml.append("</SellerSKU>");
        }
        if (isSetFulfillmentNetworkSKU()) {
            xml.append("<FulfillmentNetworkSKU>");
            xml.append(escapeXML(getFulfillmentNetworkSKU()));
            xml.append("</FulfillmentNetworkSKU>");
        }
        if (isSetQuantityShipped()) {
            xml.append("<QuantityShipped>");
            xml.append(getQuantityShipped() + "");
            xml.append("</QuantityShipped>");
        }
        if (isSetQuantityReceived()) {
            xml.append("<QuantityReceived>");
            xml.append(getQuantityReceived() + "");
            xml.append("</QuantityReceived>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetShipmentId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("ShipmentId"));
            json.append(" : ");
            json.append(quoteJSON(getShipmentId()));
            first = false;
        }
        if (isSetSellerSKU()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SellerSKU"));
            json.append(" : ");
            json.append(quoteJSON(getSellerSKU()));
            first = false;
        }
        if (isSetFulfillmentNetworkSKU()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("FulfillmentNetworkSKU"));
            json.append(" : ");
            json.append(quoteJSON(getFulfillmentNetworkSKU()));
            first = false;
        }
        if (isSetQuantityShipped()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("QuantityShipped"));
            json.append(" : ");
            json.append(quoteJSON(getQuantityShipped() + ""));
            first = false;
        }
        if (isSetQuantityReceived()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("QuantityReceived"));
            json.append(" : ");
            json.append(quoteJSON(getQuantityReceived() + ""));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
