
package com.amazonservices.mws.FulfillmentInboundShipment._2010_10_01.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InboundShipmentPlanItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InboundShipmentPlanItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SellerSKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FulfillmentNetworkSKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Oct 22 09:48:20 UTC 2010
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InboundShipmentPlanItem", propOrder = {
    "sellerSKU",
    "fulfillmentNetworkSKU",
    "quantity"
})
public class InboundShipmentPlanItem {

    @XmlElement(name = "SellerSKU")
    protected String sellerSKU;
    @XmlElement(name = "FulfillmentNetworkSKU")
    protected String fulfillmentNetworkSKU;
    @XmlElement(name = "Quantity")
    protected Integer quantity;

    /**
     * Default constructor
     * 
     */
    public InboundShipmentPlanItem() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public InboundShipmentPlanItem(final String sellerSKU, final String fulfillmentNetworkSKU, final Integer quantity) {
        this.sellerSKU = sellerSKU;
        this.fulfillmentNetworkSKU = fulfillmentNetworkSKU;
        this.quantity = quantity;
    }

    /**
     * Gets the value of the sellerSKU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerSKU() {
        return sellerSKU;
    }

    /**
     * Sets the value of the sellerSKU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerSKU(String value) {
        this.sellerSKU = value;
    }

    public boolean isSetSellerSKU() {
        return (this.sellerSKU!= null);
    }

    /**
     * Gets the value of the fulfillmentNetworkSKU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillmentNetworkSKU() {
        return fulfillmentNetworkSKU;
    }

    /**
     * Sets the value of the fulfillmentNetworkSKU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillmentNetworkSKU(String value) {
        this.fulfillmentNetworkSKU = value;
    }

    public boolean isSetFulfillmentNetworkSKU() {
        return (this.fulfillmentNetworkSKU!= null);
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQuantity(Integer value) {
        this.quantity = value;
    }

    public boolean isSetQuantity() {
        return (this.quantity!= null);
    }

    /**
     * Sets the value of the SellerSKU property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InboundShipmentPlanItem withSellerSKU(String value) {
        setSellerSKU(value);
        return this;
    }

    /**
     * Sets the value of the FulfillmentNetworkSKU property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InboundShipmentPlanItem withFulfillmentNetworkSKU(String value) {
        setFulfillmentNetworkSKU(value);
        return this;
    }

    /**
     * Sets the value of the Quantity property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InboundShipmentPlanItem withQuantity(Integer value) {
        setQuantity(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetSellerSKU()) {
            xml.append("<SellerSKU>");
            xml.append(escapeXML(getSellerSKU()));
            xml.append("</SellerSKU>");
        }
        if (isSetFulfillmentNetworkSKU()) {
            xml.append("<FulfillmentNetworkSKU>");
            xml.append(escapeXML(getFulfillmentNetworkSKU()));
            xml.append("</FulfillmentNetworkSKU>");
        }
        if (isSetQuantity()) {
            xml.append("<Quantity>");
            xml.append(getQuantity() + "");
            xml.append("</Quantity>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetSellerSKU()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SellerSKU"));
            json.append(" : ");
            json.append(quoteJSON(getSellerSKU()));
            first = false;
        }
        if (isSetFulfillmentNetworkSKU()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("FulfillmentNetworkSKU"));
            json.append(" : ");
            json.append(quoteJSON(getFulfillmentNetworkSKU()));
            first = false;
        }
        if (isSetQuantity()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Quantity"));
            json.append(" : ");
            json.append(quoteJSON(getQuantity() + ""));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
