
package com.amazonservices.mws.FulfillmentInboundShipment._2010_10_01.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SellerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Marketplace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipmentStatusList" type="{http://mws.amazonaws.com/FulfillmentInboundShipment/2010-10-01/}ShipmentStatusList" minOccurs="0"/>
 *         &lt;element name="ShipmentIdList" type="{http://mws.amazonaws.com/FulfillmentInboundShipment/2010-10-01/}ShipmentIdList" minOccurs="0"/>
 *         &lt;element name="LastUpdatedBefore" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LastUpdatedAfter" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Wed Mar 02 02:46:31 UTC 2011
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sellerId",
    "marketplace",
    "shipmentStatusList",
    "shipmentIdList",
    "lastUpdatedBefore",
    "lastUpdatedAfter"
})
@XmlRootElement(name = "ListInboundShipmentsRequest")
public class ListInboundShipmentsRequest {

    @XmlElement(name = "SellerId", required = true)
    protected String sellerId;
    @XmlElement(name = "Marketplace")
    protected String marketplace;
    @XmlElement(name = "ShipmentStatusList")
    protected ShipmentStatusList shipmentStatusList;
    @XmlElement(name = "ShipmentIdList")
    protected ShipmentIdList shipmentIdList;
    @XmlElement(name = "LastUpdatedBefore")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdatedBefore;
    @XmlElement(name = "LastUpdatedAfter")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdatedAfter;

    /**
     * Default constructor
     * 
     */
    public ListInboundShipmentsRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public ListInboundShipmentsRequest(final String sellerId, final String marketplace, final ShipmentStatusList shipmentStatusList, final ShipmentIdList shipmentIdList, final XMLGregorianCalendar lastUpdatedBefore, final XMLGregorianCalendar lastUpdatedAfter) {
        this.sellerId = sellerId;
        this.marketplace = marketplace;
        this.shipmentStatusList = shipmentStatusList;
        this.shipmentIdList = shipmentIdList;
        this.lastUpdatedBefore = lastUpdatedBefore;
        this.lastUpdatedAfter = lastUpdatedAfter;
    }

    /**
     * Gets the value of the sellerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * Sets the value of the sellerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerId(String value) {
        this.sellerId = value;
    }

    public boolean isSetSellerId() {
        return (this.sellerId!= null);
    }

    /**
     * Gets the value of the marketplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketplace() {
        return marketplace;
    }

    /**
     * Sets the value of the marketplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketplace(String value) {
        this.marketplace = value;
    }

    public boolean isSetMarketplace() {
        return (this.marketplace!= null);
    }

    /**
     * Gets the value of the shipmentStatusList property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentStatusList }
     *     
     */
    public ShipmentStatusList getShipmentStatusList() {
        return shipmentStatusList;
    }

    /**
     * Sets the value of the shipmentStatusList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentStatusList }
     *     
     */
    public void setShipmentStatusList(ShipmentStatusList value) {
        this.shipmentStatusList = value;
    }

    public boolean isSetShipmentStatusList() {
        return (this.shipmentStatusList!= null);
    }

    /**
     * Gets the value of the shipmentIdList property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentIdList }
     *     
     */
    public ShipmentIdList getShipmentIdList() {
        return shipmentIdList;
    }

    /**
     * Sets the value of the shipmentIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentIdList }
     *     
     */
    public void setShipmentIdList(ShipmentIdList value) {
        this.shipmentIdList = value;
    }

    public boolean isSetShipmentIdList() {
        return (this.shipmentIdList!= null);
    }

    /**
     * Gets the value of the lastUpdatedBefore property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedBefore() {
        return lastUpdatedBefore;
    }

    /**
     * Sets the value of the lastUpdatedBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedBefore(XMLGregorianCalendar value) {
        this.lastUpdatedBefore = value;
    }

    public boolean isSetLastUpdatedBefore() {
        return (this.lastUpdatedBefore!= null);
    }

    /**
     * Gets the value of the lastUpdatedAfter property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedAfter() {
        return lastUpdatedAfter;
    }

    /**
     * Sets the value of the lastUpdatedAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedAfter(XMLGregorianCalendar value) {
        this.lastUpdatedAfter = value;
    }

    public boolean isSetLastUpdatedAfter() {
        return (this.lastUpdatedAfter!= null);
    }

    /**
     * Sets the value of the SellerId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListInboundShipmentsRequest withSellerId(String value) {
        setSellerId(value);
        return this;
    }

    /**
     * Sets the value of the Marketplace property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListInboundShipmentsRequest withMarketplace(String value) {
        setMarketplace(value);
        return this;
    }

    /**
     * Sets the value of the ShipmentStatusList property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListInboundShipmentsRequest withShipmentStatusList(ShipmentStatusList value) {
        setShipmentStatusList(value);
        return this;
    }

    /**
     * Sets the value of the ShipmentIdList property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListInboundShipmentsRequest withShipmentIdList(ShipmentIdList value) {
        setShipmentIdList(value);
        return this;
    }

    /**
     * Sets the value of the LastUpdatedBefore property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListInboundShipmentsRequest withLastUpdatedBefore(XMLGregorianCalendar value) {
        setLastUpdatedBefore(value);
        return this;
    }

    /**
     * Sets the value of the LastUpdatedAfter property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListInboundShipmentsRequest withLastUpdatedAfter(XMLGregorianCalendar value) {
        setLastUpdatedAfter(value);
        return this;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetSellerId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SellerId"));
            json.append(" : ");
            json.append(quoteJSON(getSellerId()));
            first = false;
        }
        if (isSetMarketplace()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Marketplace"));
            json.append(" : ");
            json.append(quoteJSON(getMarketplace()));
            first = false;
        }
        if (isSetShipmentStatusList()) {
            if (!first) json.append(", ");
            json.append("\"ShipmentStatusList\" : {");
            ShipmentStatusList  shipmentStatusList = getShipmentStatusList();


            json.append(shipmentStatusList.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetShipmentIdList()) {
            if (!first) json.append(", ");
            json.append("\"ShipmentIdList\" : {");
            ShipmentIdList  shipmentIdList = getShipmentIdList();


            json.append(shipmentIdList.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetLastUpdatedBefore()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("LastUpdatedBefore"));
            json.append(" : ");
            json.append(quoteJSON(getLastUpdatedBefore() + ""));
            first = false;
        }
        if (isSetLastUpdatedAfter()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("LastUpdatedAfter"));
            json.append(" : ");
            json.append(quoteJSON(getLastUpdatedAfter() + ""));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
