
package com.amazonservices.mws.FulfillmentInboundShipment._2010_10_01.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemData" type="{http://mws.amazonaws.com/FulfillmentInboundShipment/2010-10-01/}InboundShipmentItemList" minOccurs="0"/>
 *         &lt;element name="NextToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Oct 22 09:48:20 UTC 2010
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemData",
    "nextToken"
})
@XmlRootElement(name = "ListInboundShipmentItemsByNextTokenResult")
public class ListInboundShipmentItemsByNextTokenResult {

    @XmlElement(name = "ItemData")
    protected InboundShipmentItemList itemData;
    @XmlElement(name = "NextToken")
    protected String nextToken;

    /**
     * Default constructor
     * 
     */
    public ListInboundShipmentItemsByNextTokenResult() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public ListInboundShipmentItemsByNextTokenResult(final InboundShipmentItemList itemData, final String nextToken) {
        this.itemData = itemData;
        this.nextToken = nextToken;
    }

    /**
     * Gets the value of the itemData property.
     * 
     * @return
     *     possible object is
     *     {@link InboundShipmentItemList }
     *     
     */
    public InboundShipmentItemList getItemData() {
        return itemData;
    }

    /**
     * Sets the value of the itemData property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundShipmentItemList }
     *     
     */
    public void setItemData(InboundShipmentItemList value) {
        this.itemData = value;
    }

    public boolean isSetItemData() {
        return (this.itemData!= null);
    }

    /**
     * Gets the value of the nextToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextToken() {
        return nextToken;
    }

    /**
     * Sets the value of the nextToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextToken(String value) {
        this.nextToken = value;
    }

    public boolean isSetNextToken() {
        return (this.nextToken!= null);
    }

    /**
     * Sets the value of the ItemData property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListInboundShipmentItemsByNextTokenResult withItemData(InboundShipmentItemList value) {
        setItemData(value);
        return this;
    }

    /**
     * Sets the value of the NextToken property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListInboundShipmentItemsByNextTokenResult withNextToken(String value) {
        setNextToken(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetItemData()) {
            InboundShipmentItemList  itemData = getItemData();
            xml.append("<ItemData>");
            xml.append(itemData.toXMLFragment());
            xml.append("</ItemData>");
        } 
        if (isSetNextToken()) {
            xml.append("<NextToken>");
            xml.append(escapeXML(getNextToken()));
            xml.append("</NextToken>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetItemData()) {
            if (!first) json.append(", ");
            json.append("\"ItemData\" : {");
            InboundShipmentItemList  itemData = getItemData();


            json.append(itemData.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetNextToken()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("NextToken"));
            json.append(" : ");
            json.append(quoteJSON(getNextToken()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
