
package com.amazonservices.mws.FulfillmentInboundShipment._2010_10_01.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://mws.amazonaws.com/FulfillmentInboundShipment/2010-10-01/}ListInboundShipmentsByNextTokenResult"/>
 *         &lt;element ref="{http://mws.amazonaws.com/FulfillmentInboundShipment/2010-10-01/}ResponseMetadata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Oct 22 09:48:20 UTC 2010
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listInboundShipmentsByNextTokenResult",
    "responseMetadata"
})
@XmlRootElement(name = "ListInboundShipmentsByNextTokenResponse")
public class ListInboundShipmentsByNextTokenResponse {

    @XmlElement(name = "ListInboundShipmentsByNextTokenResult", required = true)
    protected ListInboundShipmentsByNextTokenResult listInboundShipmentsByNextTokenResult;
    @XmlElement(name = "ResponseMetadata", required = true)
    protected ResponseMetadata responseMetadata;

    /**
     * Default constructor
     * 
     */
    public ListInboundShipmentsByNextTokenResponse() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public ListInboundShipmentsByNextTokenResponse(final ListInboundShipmentsByNextTokenResult listInboundShipmentsByNextTokenResult, final ResponseMetadata responseMetadata) {
        this.listInboundShipmentsByNextTokenResult = listInboundShipmentsByNextTokenResult;
        this.responseMetadata = responseMetadata;
    }

    /**
     * Gets the value of the listInboundShipmentsByNextTokenResult property.
     * 
     * @return
     *     possible object is
     *     {@link ListInboundShipmentsByNextTokenResult }
     *     
     */
    public ListInboundShipmentsByNextTokenResult getListInboundShipmentsByNextTokenResult() {
        return listInboundShipmentsByNextTokenResult;
    }

    /**
     * Sets the value of the listInboundShipmentsByNextTokenResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListInboundShipmentsByNextTokenResult }
     *     
     */
    public void setListInboundShipmentsByNextTokenResult(ListInboundShipmentsByNextTokenResult value) {
        this.listInboundShipmentsByNextTokenResult = value;
    }

    public boolean isSetListInboundShipmentsByNextTokenResult() {
        return (this.listInboundShipmentsByNextTokenResult!= null);
    }

    /**
     * Gets the value of the responseMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMetadata }
     *     
     */
    public ResponseMetadata getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Sets the value of the responseMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMetadata }
     *     
     */
    public void setResponseMetadata(ResponseMetadata value) {
        this.responseMetadata = value;
    }

    public boolean isSetResponseMetadata() {
        return (this.responseMetadata!= null);
    }

    /**
     * Sets the value of the ListInboundShipmentsByNextTokenResult property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListInboundShipmentsByNextTokenResponse withListInboundShipmentsByNextTokenResult(ListInboundShipmentsByNextTokenResult value) {
        setListInboundShipmentsByNextTokenResult(value);
        return this;
    }

    /**
     * Sets the value of the ResponseMetadata property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListInboundShipmentsByNextTokenResponse withResponseMetadata(ResponseMetadata value) {
        setResponseMetadata(value);
        return this;
    }
    

    /**
     * 
     * XML string representation of this object
     * 
     * @return XML String
     */
    public String toXML() {
        StringBuffer xml = new StringBuffer();
        xml.append("<ListInboundShipmentsByNextTokenResponse xmlns=\"http://mws.amazonaws.com/FulfillmentInboundShipment/2010-10-01/\">");
        if (isSetListInboundShipmentsByNextTokenResult()) {
            ListInboundShipmentsByNextTokenResult  listInboundShipmentsByNextTokenResult = getListInboundShipmentsByNextTokenResult();
            xml.append("<ListInboundShipmentsByNextTokenResult>");
            xml.append(listInboundShipmentsByNextTokenResult.toXMLFragment());
            xml.append("</ListInboundShipmentsByNextTokenResult>");
        } 
        if (isSetResponseMetadata()) {
            ResponseMetadata  responseMetadata = getResponseMetadata();
            xml.append("<ResponseMetadata>");
            xml.append(responseMetadata.toXMLFragment());
            xml.append("</ResponseMetadata>");
        } 
        xml.append("</ListInboundShipmentsByNextTokenResponse>");
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     * 
     * JSON string representation of this object
     * 
     * @return JSON String
     */
    public String toJSON() {
        StringBuffer json = new StringBuffer();
        json.append("{\"ListInboundShipmentsByNextTokenResponse\" : {");
        json.append(quoteJSON("@xmlns"));
        json.append(" : ");
        json.append(quoteJSON("http://mws.amazonaws.com/FulfillmentInboundShipment/2010-10-01/"));
        boolean first = true;
        json.append(", ");
        if (isSetListInboundShipmentsByNextTokenResult()) {
            if (!first) json.append(", ");
            json.append("\"ListInboundShipmentsByNextTokenResult\" : {");
            ListInboundShipmentsByNextTokenResult  listInboundShipmentsByNextTokenResult = getListInboundShipmentsByNextTokenResult();

            json.append(listInboundShipmentsByNextTokenResult.toJSONFragment());
            json.append("}");
            first = false;
        } 
        if (isSetResponseMetadata()) {
            if (!first) json.append(", ");
            json.append("\"ResponseMetadata\" : {");
            ResponseMetadata  responseMetadata = getResponseMetadata();

            json.append(responseMetadata.toJSONFragment());
            json.append("}");
            first = false;
        } 
        json.append("}");
        json.append("}");
        return json.toString();
    }

    /**
     * 
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
                }
            }
        }
        sb.append("\"");
        return sb.toString();
    }


}
