
package com.amazonservices.mws.FulfillmentInboundShipment._2010_10_01.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SellerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Marketplace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipmentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InboundShipmentHeader" type="{http://mws.amazonaws.com/FulfillmentInboundShipment/2010-10-01/}InboundShipmentHeader" minOccurs="0"/>
 *         &lt;element name="InboundShipmentItems" type="{http://mws.amazonaws.com/FulfillmentInboundShipment/2010-10-01/}InboundShipmentItemList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Oct 22 09:48:20 UTC 2010
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sellerId",
    "marketplace",
    "shipmentId",
    "inboundShipmentHeader",
    "inboundShipmentItems"
})
@XmlRootElement(name = "UpdateInboundShipmentRequest")
public class UpdateInboundShipmentRequest {

    @XmlElement(name = "SellerId", required = true)
    protected String sellerId;
    @XmlElement(name = "Marketplace")
    protected String marketplace;
    @XmlElement(name = "ShipmentId", required = true)
    protected String shipmentId;
    @XmlElement(name = "InboundShipmentHeader")
    protected InboundShipmentHeader inboundShipmentHeader;
    @XmlElement(name = "InboundShipmentItems")
    protected InboundShipmentItemList inboundShipmentItems;

    /**
     * Default constructor
     * 
     */
    public UpdateInboundShipmentRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public UpdateInboundShipmentRequest(final String sellerId, final String marketplace, final String shipmentId, final InboundShipmentHeader inboundShipmentHeader, final InboundShipmentItemList inboundShipmentItems) {
        this.sellerId = sellerId;
        this.marketplace = marketplace;
        this.shipmentId = shipmentId;
        this.inboundShipmentHeader = inboundShipmentHeader;
        this.inboundShipmentItems = inboundShipmentItems;
    }

    /**
     * Gets the value of the sellerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * Sets the value of the sellerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerId(String value) {
        this.sellerId = value;
    }

    public boolean isSetSellerId() {
        return (this.sellerId!= null);
    }

    /**
     * Gets the value of the marketplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketplace() {
        return marketplace;
    }

    /**
     * Sets the value of the marketplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketplace(String value) {
        this.marketplace = value;
    }

    public boolean isSetMarketplace() {
        return (this.marketplace!= null);
    }

    /**
     * Gets the value of the shipmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentId() {
        return shipmentId;
    }

    /**
     * Sets the value of the shipmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentId(String value) {
        this.shipmentId = value;
    }

    public boolean isSetShipmentId() {
        return (this.shipmentId!= null);
    }

    /**
     * Gets the value of the inboundShipmentHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InboundShipmentHeader }
     *     
     */
    public InboundShipmentHeader getInboundShipmentHeader() {
        return inboundShipmentHeader;
    }

    /**
     * Sets the value of the inboundShipmentHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundShipmentHeader }
     *     
     */
    public void setInboundShipmentHeader(InboundShipmentHeader value) {
        this.inboundShipmentHeader = value;
    }

    public boolean isSetInboundShipmentHeader() {
        return (this.inboundShipmentHeader!= null);
    }

    /**
     * Gets the value of the inboundShipmentItems property.
     * 
     * @return
     *     possible object is
     *     {@link InboundShipmentItemList }
     *     
     */
    public InboundShipmentItemList getInboundShipmentItems() {
        return inboundShipmentItems;
    }

    /**
     * Sets the value of the inboundShipmentItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundShipmentItemList }
     *     
     */
    public void setInboundShipmentItems(InboundShipmentItemList value) {
        this.inboundShipmentItems = value;
    }

    public boolean isSetInboundShipmentItems() {
        return (this.inboundShipmentItems!= null);
    }

    /**
     * Sets the value of the SellerId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public UpdateInboundShipmentRequest withSellerId(String value) {
        setSellerId(value);
        return this;
    }

    /**
     * Sets the value of the Marketplace property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public UpdateInboundShipmentRequest withMarketplace(String value) {
        setMarketplace(value);
        return this;
    }

    /**
     * Sets the value of the ShipmentId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public UpdateInboundShipmentRequest withShipmentId(String value) {
        setShipmentId(value);
        return this;
    }

    /**
     * Sets the value of the InboundShipmentHeader property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public UpdateInboundShipmentRequest withInboundShipmentHeader(InboundShipmentHeader value) {
        setInboundShipmentHeader(value);
        return this;
    }

    /**
     * Sets the value of the InboundShipmentItems property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public UpdateInboundShipmentRequest withInboundShipmentItems(InboundShipmentItemList value) {
        setInboundShipmentItems(value);
        return this;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetSellerId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SellerId"));
            json.append(" : ");
            json.append(quoteJSON(getSellerId()));
            first = false;
        }
        if (isSetMarketplace()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Marketplace"));
            json.append(" : ");
            json.append(quoteJSON(getMarketplace()));
            first = false;
        }
        if (isSetShipmentId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("ShipmentId"));
            json.append(" : ");
            json.append(quoteJSON(getShipmentId()));
            first = false;
        }
        if (isSetInboundShipmentHeader()) {
            if (!first) json.append(", ");
            json.append("\"InboundShipmentHeader\" : {");
            InboundShipmentHeader  inboundShipmentHeader = getInboundShipmentHeader();


            json.append(inboundShipmentHeader.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetInboundShipmentItems()) {
            if (!first) json.append(", ");
            json.append("\"InboundShipmentItems\" : {");
            InboundShipmentItemList  inboundShipmentItems = getInboundShipmentItems();


            json.append(inboundShipmentItems.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
