
package com.amazonservices.mws.sellers.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{https://mws.amazonservices.com/Sellers/2011-07-01}ListMarketplaceParticipationsByNextTokenResult"/>
 *         &lt;element ref="{https://mws.amazonservices.com/Sellers/2011-07-01}ResponseMetadata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Jun 24 20:08:14 GMT 2011
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listMarketplaceParticipationsByNextTokenResult",
    "responseMetadata"
})
@XmlRootElement(name = "ListMarketplaceParticipationsByNextTokenResponse")
public class ListMarketplaceParticipationsByNextTokenResponse {

    @XmlElement(name = "ListMarketplaceParticipationsByNextTokenResult", required = true)
    protected ListMarketplaceParticipationsByNextTokenResult listMarketplaceParticipationsByNextTokenResult;
    @XmlElement(name = "ResponseMetadata", required = true)
    protected ResponseMetadata responseMetadata;

    /**
     * Default constructor
     * 
     */
    public ListMarketplaceParticipationsByNextTokenResponse() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public ListMarketplaceParticipationsByNextTokenResponse(final ListMarketplaceParticipationsByNextTokenResult listMarketplaceParticipationsByNextTokenResult, final ResponseMetadata responseMetadata) {
        this.listMarketplaceParticipationsByNextTokenResult = listMarketplaceParticipationsByNextTokenResult;
        this.responseMetadata = responseMetadata;
    }

    /**
     * Gets the value of the listMarketplaceParticipationsByNextTokenResult property.
     * 
     * @return
     *     possible object is
     *     {@link ListMarketplaceParticipationsByNextTokenResult }
     *     
     */
    public ListMarketplaceParticipationsByNextTokenResult getListMarketplaceParticipationsByNextTokenResult() {
        return listMarketplaceParticipationsByNextTokenResult;
    }

    /**
     * Sets the value of the listMarketplaceParticipationsByNextTokenResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListMarketplaceParticipationsByNextTokenResult }
     *     
     */
    public void setListMarketplaceParticipationsByNextTokenResult(ListMarketplaceParticipationsByNextTokenResult value) {
        this.listMarketplaceParticipationsByNextTokenResult = value;
    }

    public boolean isSetListMarketplaceParticipationsByNextTokenResult() {
        return (this.listMarketplaceParticipationsByNextTokenResult!= null);
    }

    /**
     * Gets the value of the responseMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMetadata }
     *     
     */
    public ResponseMetadata getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Sets the value of the responseMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMetadata }
     *     
     */
    public void setResponseMetadata(ResponseMetadata value) {
        this.responseMetadata = value;
    }

    public boolean isSetResponseMetadata() {
        return (this.responseMetadata!= null);
    }

    /**
     * Sets the value of the ListMarketplaceParticipationsByNextTokenResult property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListMarketplaceParticipationsByNextTokenResponse withListMarketplaceParticipationsByNextTokenResult(ListMarketplaceParticipationsByNextTokenResult value) {
        setListMarketplaceParticipationsByNextTokenResult(value);
        return this;
    }

    /**
     * Sets the value of the ResponseMetadata property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListMarketplaceParticipationsByNextTokenResponse withResponseMetadata(ResponseMetadata value) {
        setResponseMetadata(value);
        return this;
    }
    

    /**
     * 
     * XML string representation of this object
     * 
     * @return XML String
     */
    public String toXML() {
        StringBuffer xml = new StringBuffer();
        xml.append("<ListMarketplaceParticipationsByNextTokenResponse xmlns=\"https://mws.amazonservices.com/Sellers/2011-07-01\">");
        if (isSetListMarketplaceParticipationsByNextTokenResult()) {
            ListMarketplaceParticipationsByNextTokenResult  listMarketplaceParticipationsByNextTokenResult = getListMarketplaceParticipationsByNextTokenResult();
            xml.append("<ListMarketplaceParticipationsByNextTokenResult>");
            xml.append(listMarketplaceParticipationsByNextTokenResult.toXMLFragment());
            xml.append("</ListMarketplaceParticipationsByNextTokenResult>");
        } 
        if (isSetResponseMetadata()) {
            ResponseMetadata  responseMetadata = getResponseMetadata();
            xml.append("<ResponseMetadata>");
            xml.append(responseMetadata.toXMLFragment());
            xml.append("</ResponseMetadata>");
        } 
        xml.append("</ListMarketplaceParticipationsByNextTokenResponse>");
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    @SuppressWarnings("unused")
	private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     * 
     * JSON string representation of this object
     * 
     * @return JSON String
     */
    public String toJSON() {
        StringBuffer json = new StringBuffer();
        json.append("{\"ListMarketplaceParticipationsByNextTokenResponse\" : {");
        json.append(quoteJSON("@xmlns"));
        json.append(" : ");
        json.append(quoteJSON("https://mws.amazonservices.com/Sellers/2011-07-01"));
        boolean first = true;
        json.append(", ");
        if (isSetListMarketplaceParticipationsByNextTokenResult()) {
            if (!first) json.append(", ");
            json.append("\"ListMarketplaceParticipationsByNextTokenResult\" : {");
            ListMarketplaceParticipationsByNextTokenResult  listMarketplaceParticipationsByNextTokenResult = getListMarketplaceParticipationsByNextTokenResult();

            json.append(listMarketplaceParticipationsByNextTokenResult.toJSONFragment());
            json.append("}");
            first = false;
        } 
        if (isSetResponseMetadata()) {
            if (!first) json.append(", ");
            json.append("\"ResponseMetadata\" : {");
            ResponseMetadata  responseMetadata = getResponseMetadata();

            json.append(responseMetadata.toJSONFragment());
            json.append("}");
            first = false;
        } 
        json.append("}");
        json.append("}");
        return json.toString();
    }

    /**
     * 
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
                }
            }
        }
        sb.append("\"");
        return sb.toString();
    }


}
