
package com.amazonservices.mws.sellers.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ListMarketplaces complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListMarketplaces">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Marketplace" type="{https://mws.amazonservices.com/Sellers/2011-07-01}Marketplace" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Jun 24 20:08:14 GMT 2011
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListMarketplaces", propOrder = {
    "marketplace"
})
public class ListMarketplaces {

    @XmlElement(name = "Marketplace", required = true)
    protected List<Marketplace> marketplace;

    /**
     * Default constructor
     * 
     */
    public ListMarketplaces() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public ListMarketplaces(final List<Marketplace> marketplace) {
        this.marketplace = marketplace;
    }

    /**
     * Gets the value of the marketplace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marketplace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarketplace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Marketplace }
     * 
     * 
     */
    public List<Marketplace> getMarketplace() {
        if (marketplace == null) {
            marketplace = new ArrayList<Marketplace>();
        }
        return this.marketplace;
    }

    public boolean isSetMarketplace() {
        return ((this.marketplace!= null)&&(!this.marketplace.isEmpty()));
    }

    public void unsetMarketplace() {
        this.marketplace = null;
    }

    /**
     * Sets the value of the Marketplace property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public ListMarketplaces withMarketplace(Marketplace... values) {
        for (Marketplace value: values) {
            getMarketplace().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the marketplace property.
     * 
     * @param marketplace
     *     allowed object is
     *     {@link Marketplace }
     *     
     */
    public void setMarketplace(List<Marketplace> marketplace) {
        this.marketplace = marketplace;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        java.util.List<Marketplace> marketplaceList = getMarketplace();
        for (Marketplace marketplace : marketplaceList) {
            xml.append("<Marketplace>");
            xml.append(marketplace.toXMLFragment());
            xml.append("</Marketplace>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    @SuppressWarnings("unused")
	private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetMarketplace()) {
            if (!first) json.append(", ");
            json.append("\"Marketplace\" : [");
            java.util.List<Marketplace> marketplaceList = getMarketplace();
            int marketplaceListIndex = 0;
            for (Marketplace marketplace : marketplaceList) {
                if (marketplaceListIndex > 0) json.append(", ");
                json.append("{");
                json.append("");
                json.append(marketplace.toJSONFragment());
                json.append("}");
                first = false;
                ++marketplaceListIndex;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    @SuppressWarnings("unused")
	private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
