
package com.amazonservices.mws.sellers.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NextToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ListParticipations" type="{https://mws.amazonservices.com/Sellers/2011-07-01}ListParticipations"/>
 *         &lt;element name="ListMarketplaces" type="{https://mws.amazonservices.com/Sellers/2011-07-01}ListMarketplaces"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Jun 24 20:08:14 GMT 2011
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nextToken",
    "listParticipations",
    "listMarketplaces"
})
@XmlRootElement(name = "ListMarketplaceParticipationsByNextTokenResult")
public class ListMarketplaceParticipationsByNextTokenResult {

    @XmlElement(name = "NextToken")
    protected String nextToken;
    @XmlElement(name = "ListParticipations", required = true)
    protected ListParticipations listParticipations;
    @XmlElement(name = "ListMarketplaces", required = true)
    protected ListMarketplaces listMarketplaces;

    /**
     * Default constructor
     * 
     */
    public ListMarketplaceParticipationsByNextTokenResult() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public ListMarketplaceParticipationsByNextTokenResult(final String nextToken, final ListParticipations listParticipations, final ListMarketplaces listMarketplaces) {
        this.nextToken = nextToken;
        this.listParticipations = listParticipations;
        this.listMarketplaces = listMarketplaces;
    }

    /**
     * Gets the value of the nextToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextToken() {
        return nextToken;
    }

    /**
     * Sets the value of the nextToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextToken(String value) {
        this.nextToken = value;
    }

    public boolean isSetNextToken() {
        return (this.nextToken!= null);
    }

    /**
     * Gets the value of the ListParticipations property.
     * 
     * @return
     *     possible object is
     *     {@link ListParticipations }
     *     
     */
    public ListParticipations getListParticipations() {
        return listParticipations;
    }

    /**
     * Sets the value of the ListParticipations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListParticipations }
     *     
     */
    public void setListParticipations(ListParticipations value) {
        this.listParticipations = value;
    }

    public boolean isSetListParticipations() {
        return (this.listParticipations!= null);
    }

    /**
     * Gets the value of the ListMarketplaces property.
     * 
     * @return
     *     possible object is
     *     {@link ListMarketplaces }
     *     
     */
    public ListMarketplaces getListMarketplaces() {
        return listMarketplaces;
    }

    /**
     * Sets the value of the ListMarketplaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListMarketplaces }
     *     
     */
    public void setListMarketplaces(ListMarketplaces value) {
        this.listMarketplaces = value;
    }

    public boolean isSetListMarketplaces() {
        return (this.listMarketplaces!= null);
    }

    /**
     * Sets the value of the NextToken property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListMarketplaceParticipationsByNextTokenResult withNextToken(String value) {
        setNextToken(value);
        return this;
    }

    /**
     * Sets the value of the ListParticipations property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListMarketplaceParticipationsByNextTokenResult withListParticipations(ListParticipations value) {
        setListParticipations(value);
        return this;
    }

    /**
     * Sets the value of the ListMarketplaces property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListMarketplaceParticipationsByNextTokenResult withListMarketplaces(ListMarketplaces value) {
        setListMarketplaces(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetNextToken()) {
            xml.append("<NextToken>");
            xml.append(escapeXML(getNextToken()));
            xml.append("</NextToken>");
        }
        if (isSetListParticipations()) {
            ListParticipations  ListParticipations = getListParticipations();
            xml.append("<ListParticipations>");
            xml.append(ListParticipations.toXMLFragment());
            xml.append("</ListParticipations>");
        } 
        if (isSetListMarketplaces()) {
            ListMarketplaces  ListMarketplaces = getListMarketplaces();
            xml.append("<ListMarketplaces>");
            xml.append(ListMarketplaces.toXMLFragment());
            xml.append("</ListMarketplaces>");
        } 
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetNextToken()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("NextToken"));
            json.append(" : ");
            json.append(quoteJSON(getNextToken()));
            first = false;
        }
        if (isSetListParticipations()) {
            if (!first) json.append(", ");
            json.append("\"ListParticipations\" : {");
            ListParticipations  ListParticipations = getListParticipations();


            json.append(ListParticipations.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetListMarketplaces()) {
            if (!first) json.append(", ");
            json.append("\"ListMarketplaces\" : {");
            ListMarketplaces  ListMarketplaces = getListMarketplaces();


            json.append(ListMarketplaces.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
