
package com.amazonservices.mws.sellers.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Participation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Participation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MarketplaceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SellerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HasSellerSuspendedListings" type="{https://mws.amazonservices.com/Sellers/2011-07-01}HasSellerSuspendedListingsEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Jun 24 20:08:14 GMT 2011
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Participation", propOrder = {
    "marketplaceId",
    "sellerId",
    "hasSellerSuspendedListings"
})
public class Participation {

    @XmlElement(name = "MarketplaceId")
    protected String marketplaceId;
    @XmlElement(name = "SellerId")
    protected String sellerId;
    @XmlElement(name = "HasSellerSuspendedListings")
    protected HasSellerSuspendedListingsEnum hasSellerSuspendedListings;

    /**
     * Default constructor
     * 
     */
    public Participation() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public Participation(final String marketplaceId, final String sellerId, final HasSellerSuspendedListingsEnum hasSellerSuspendedListings) {
        this.marketplaceId = marketplaceId;
        this.sellerId = sellerId;
        this.hasSellerSuspendedListings = hasSellerSuspendedListings;
    }

    /**
     * Gets the value of the marketplaceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketplaceId() {
        return marketplaceId;
    }

    /**
     * Sets the value of the marketplaceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketplaceId(String value) {
        this.marketplaceId = value;
    }

    public boolean isSetMarketplaceId() {
        return (this.marketplaceId!= null);
    }

    /**
     * Gets the value of the sellerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * Sets the value of the sellerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerId(String value) {
        this.sellerId = value;
    }

    public boolean isSetSellerId() {
        return (this.sellerId!= null);
    }

    /**
     * Gets the value of the hasSellerSuspendedListings property.
     * 
     * @return
     *     possible object is
     *     {@link HasSellerSuspendedListingsEnum }
     *     
     */
    public HasSellerSuspendedListingsEnum getHasSellerSuspendedListings() {
        return hasSellerSuspendedListings;
    }

    /**
     * Sets the value of the hasSellerSuspendedListings property.
     * 
     * @param value
     *     allowed object is
     *     {@link HasSellerSuspendedListingsEnum }
     *     
     */
    public void setHasSellerSuspendedListings(HasSellerSuspendedListingsEnum value) {
        this.hasSellerSuspendedListings = value;
    }

    public boolean isSetHasSellerSuspendedListings() {
        return (this.hasSellerSuspendedListings!= null);
    }

    /**
     * Sets the value of the MarketplaceId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Participation withMarketplaceId(String value) {
        setMarketplaceId(value);
        return this;
    }

    /**
     * Sets the value of the SellerId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Participation withSellerId(String value) {
        setSellerId(value);
        return this;
    }

    /**
     * Sets the value of the HasSellerSuspendedListings property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public Participation withHasSellerSuspendedListings(HasSellerSuspendedListingsEnum value) {
        setHasSellerSuspendedListings(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetMarketplaceId()) {
            xml.append("<MarketplaceId>");
            xml.append(escapeXML(getMarketplaceId()));
            xml.append("</MarketplaceId>");
        }
        if (isSetSellerId()) {
            xml.append("<SellerId>");
            xml.append(escapeXML(getSellerId()));
            xml.append("</SellerId>");
        }
        if (isSetHasSellerSuspendedListings()) {
            xml.append("<HasSellerSuspendedListings>");
            xml.append(getHasSellerSuspendedListings().value());
            xml.append("</HasSellerSuspendedListings>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetMarketplaceId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("MarketplaceId"));
            json.append(" : ");
            json.append(quoteJSON(getMarketplaceId()));
            first = false;
        }
        if (isSetSellerId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SellerId"));
            json.append(" : ");
            json.append(quoteJSON(getSellerId()));
            first = false;
        }
        if (isSetHasSellerSuspendedListings()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("HasSellerSuspendedListings"));
            json.append(" : ");
            json.append(quoteJSON(getHasSellerSuspendedListings().value()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
