package com.amazonservices.mws.FulfillmentInventory._2010_10_01.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InventorySupply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InventorySupply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SellerSKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FNSKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ASIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Condition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalSupplyQuantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="InStockSupplyQuantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="EarliestAvailability" type="{http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/}Timepoint" minOccurs="0"/>
 *         &lt;element name="SupplyDetail" type="{http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/}InventorySupplyDetailList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Fri Oct 22 09:47:28 UTC 2010
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InventorySupply", propOrder = {
    "sellerSKU",
    "fnsku",
    "asin",
    "condition",
    "totalSupplyQuantity",
    "inStockSupplyQuantity",
    "earliestAvailability",
    "supplyDetail"
})
public class InventorySupply {

    @XmlElement(name = "SellerSKU")
    protected String sellerSKU;
    @XmlElement(name = "FNSKU")
    protected String fnsku;
    @XmlElement(name = "ASIN")
    protected String asin;
    @XmlElement(name = "Condition")
    protected String condition;
    @XmlElement(name = "TotalSupplyQuantity")
    protected Integer totalSupplyQuantity;
    @XmlElement(name = "InStockSupplyQuantity")
    protected Integer inStockSupplyQuantity;
    @XmlElement(name = "EarliestAvailability")
    protected Timepoint earliestAvailability;
    @XmlElement(name = "SupplyDetail")
    protected InventorySupplyDetailList supplyDetail;

    /**
     * Default constructor
     * 
     */
    public InventorySupply() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public InventorySupply(final String sellerSKU, final String fnsku, final String asin, final String condition, final Integer totalSupplyQuantity, final Integer inStockSupplyQuantity, final Timepoint earliestAvailability, final InventorySupplyDetailList supplyDetail) {
        this.sellerSKU = sellerSKU;
        this.fnsku = fnsku;
        this.asin = asin;
        this.condition = condition;
        this.totalSupplyQuantity = totalSupplyQuantity;
        this.inStockSupplyQuantity = inStockSupplyQuantity;
        this.earliestAvailability = earliestAvailability;
        this.supplyDetail = supplyDetail;
    }

    /**
     * Gets the value of the sellerSKU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerSKU() {
        return sellerSKU;
    }

    /**
     * Sets the value of the sellerSKU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerSKU(String value) {
        this.sellerSKU = value;
    }

    public boolean isSetSellerSKU() {
        return (this.sellerSKU!= null);
    }

    /**
     * Gets the value of the fnsku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFNSKU() {
        return fnsku;
    }

    /**
     * Sets the value of the fnsku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFNSKU(String value) {
        this.fnsku = value;
    }

    public boolean isSetFNSKU() {
        return (this.fnsku!= null);
    }

    /**
     * Gets the value of the asin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getASIN() {
        return asin;
    }

    /**
     * Sets the value of the asin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setASIN(String value) {
        this.asin = value;
    }

    public boolean isSetASIN() {
        return (this.asin!= null);
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    public boolean isSetCondition() {
        return (this.condition!= null);
    }

    /**
     * Gets the value of the totalSupplyQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalSupplyQuantity() {
        return totalSupplyQuantity;
    }

    /**
     * Sets the value of the totalSupplyQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalSupplyQuantity(Integer value) {
        this.totalSupplyQuantity = value;
    }

    public boolean isSetTotalSupplyQuantity() {
        return (this.totalSupplyQuantity!= null);
    }

    /**
     * Gets the value of the inStockSupplyQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInStockSupplyQuantity() {
        return inStockSupplyQuantity;
    }

    /**
     * Sets the value of the inStockSupplyQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInStockSupplyQuantity(Integer value) {
        this.inStockSupplyQuantity = value;
    }

    public boolean isSetInStockSupplyQuantity() {
        return (this.inStockSupplyQuantity!= null);
    }

    /**
     * Gets the value of the earliestAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link Timepoint }
     *     
     */
    public Timepoint getEarliestAvailability() {
        return earliestAvailability;
    }

    /**
     * Sets the value of the earliestAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timepoint }
     *     
     */
    public void setEarliestAvailability(Timepoint value) {
        this.earliestAvailability = value;
    }

    public boolean isSetEarliestAvailability() {
        return (this.earliestAvailability!= null);
    }

    /**
     * Gets the value of the supplyDetail property.
     * 
     * @return
     *     possible object is
     *     {@link InventorySupplyDetailList }
     *     
     */
    public InventorySupplyDetailList getSupplyDetail() {
        return supplyDetail;
    }

    /**
     * Sets the value of the supplyDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventorySupplyDetailList }
     *     
     */
    public void setSupplyDetail(InventorySupplyDetailList value) {
        this.supplyDetail = value;
    }

    public boolean isSetSupplyDetail() {
        return (this.supplyDetail!= null);
    }

    /**
     * Sets the value of the SellerSKU property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InventorySupply withSellerSKU(String value) {
        setSellerSKU(value);
        return this;
    }

    /**
     * Sets the value of the FNSKU property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InventorySupply withFNSKU(String value) {
        setFNSKU(value);
        return this;
    }

    /**
     * Sets the value of the ASIN property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InventorySupply withASIN(String value) {
        setASIN(value);
        return this;
    }

    /**
     * Sets the value of the Condition property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InventorySupply withCondition(String value) {
        setCondition(value);
        return this;
    }

    /**
     * Sets the value of the TotalSupplyQuantity property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InventorySupply withTotalSupplyQuantity(Integer value) {
        setTotalSupplyQuantity(value);
        return this;
    }

    /**
     * Sets the value of the InStockSupplyQuantity property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InventorySupply withInStockSupplyQuantity(Integer value) {
        setInStockSupplyQuantity(value);
        return this;
    }

    /**
     * Sets the value of the EarliestAvailability property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InventorySupply withEarliestAvailability(Timepoint value) {
        setEarliestAvailability(value);
        return this;
    }

    /**
     * Sets the value of the SupplyDetail property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InventorySupply withSupplyDetail(InventorySupplyDetailList value) {
        setSupplyDetail(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetSellerSKU()) {
            xml.append("<SellerSKU>");
            xml.append(escapeXML(getSellerSKU()));
            xml.append("</SellerSKU>");
        }
        if (isSetFNSKU()) {
            xml.append("<FNSKU>");
            xml.append(escapeXML(getFNSKU()));
            xml.append("</FNSKU>");
        }
        if (isSetASIN()) {
            xml.append("<ASIN>");
            xml.append(escapeXML(getASIN()));
            xml.append("</ASIN>");
        }
        if (isSetCondition()) {
            xml.append("<Condition>");
            xml.append(escapeXML(getCondition()));
            xml.append("</Condition>");
        }
        if (isSetTotalSupplyQuantity()) {
            xml.append("<TotalSupplyQuantity>");
            xml.append(getTotalSupplyQuantity() + "");
            xml.append("</TotalSupplyQuantity>");
        }
        if (isSetInStockSupplyQuantity()) {
            xml.append("<InStockSupplyQuantity>");
            xml.append(getInStockSupplyQuantity() + "");
            xml.append("</InStockSupplyQuantity>");
        }
        if (isSetEarliestAvailability()) {
            Timepoint  earliestAvailability = getEarliestAvailability();
            xml.append("<EarliestAvailability>");
            xml.append(earliestAvailability.toXMLFragment());
            xml.append("</EarliestAvailability>");
        } 
        if (isSetSupplyDetail()) {
            InventorySupplyDetailList  supplyDetail = getSupplyDetail();
            xml.append("<SupplyDetail>");
            xml.append(supplyDetail.toXMLFragment());
            xml.append("</SupplyDetail>");
        } 
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetSellerSKU()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SellerSKU"));
            json.append(" : ");
            json.append(quoteJSON(getSellerSKU()));
            first = false;
        }
        if (isSetFNSKU()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("FNSKU"));
            json.append(" : ");
            json.append(quoteJSON(getFNSKU()));
            first = false;
        }
        if (isSetASIN()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("ASIN"));
            json.append(" : ");
            json.append(quoteJSON(getASIN()));
            first = false;
        }
        if (isSetCondition()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Condition"));
            json.append(" : ");
            json.append(quoteJSON(getCondition()));
            first = false;
        }
        if (isSetTotalSupplyQuantity()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("TotalSupplyQuantity"));
            json.append(" : ");
            json.append(quoteJSON(getTotalSupplyQuantity() + ""));
            first = false;
        }
        if (isSetInStockSupplyQuantity()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("InStockSupplyQuantity"));
            json.append(" : ");
            json.append(quoteJSON(getInStockSupplyQuantity() + ""));
            first = false;
        }
        if (isSetEarliestAvailability()) {
            if (!first) json.append(", ");
            json.append("\"EarliestAvailability\" : {");
            Timepoint  earliestAvailability = getEarliestAvailability();


            json.append(earliestAvailability.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetSupplyDetail()) {
            if (!first) json.append(", ");
            json.append("\"SupplyDetail\" : {");
            InventorySupplyDetailList  supplyDetail = getSupplyDetail();


            json.append(supplyDetail.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
