# A sample Gemfile
source 'http://ruby.taobao.org/'
ruby '2.0.0'

gem 'celluloid', '~> 0.15'
gem 'multi_json', '~> 1.9'
gem 'oj', '~> 2.5'
gem 'httparty', '~> 0.13'
gem 'sequel', '~> 4.8'
gem 'mysql2', '~> 0.3'
gem 'nokogiri', '~> 1.6'
