//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.02 at 11:00:43 PM PHT 
//


package com.elcuk.mws.jaxb.ordertracking;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PromotionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PromotionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PromotionIDs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ItemPromotionDiscount" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ShipPromotionDiscount" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PromotionType", propOrder = {
    "promotionIDs",
    "itemPromotionDiscount",
    "shipPromotionDiscount"
})
public class PromotionType {

    @XmlElement(name = "PromotionIDs", required = true)
    protected String promotionIDs;
    @XmlElement(name = "ItemPromotionDiscount")
    protected Float itemPromotionDiscount;
    @XmlElement(name = "ShipPromotionDiscount")
    protected Float shipPromotionDiscount;

    /**
     * Gets the value of the promotionIDs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotionIDs() {
        return promotionIDs;
    }

    /**
     * Sets the value of the promotionIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotionIDs(String value) {
        this.promotionIDs = value;
    }

    /**
     * Gets the value of the itemPromotionDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getItemPromotionDiscount() {
        return itemPromotionDiscount;
    }

    /**
     * Sets the value of the itemPromotionDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setItemPromotionDiscount(Float value) {
        this.itemPromotionDiscount = value;
    }

    /**
     * Gets the value of the shipPromotionDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getShipPromotionDiscount() {
        return shipPromotionDiscount;
    }

    /**
     * Sets the value of the shipPromotionDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setShipPromotionDiscount(Float value) {
        this.shipPromotionDiscount = value;
    }

}
