//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.01 at 12:53:15 AM PHT 
//


package com.elcuk.mws.jaxb.payments;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdjustedItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdjustedItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AmazonOrderItemCode" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="MerchantAdjustmentItemID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ItemPriceAdjustments" type="{}ItemPriceAdjustmentsType"/>
 *         &lt;element name="ItemFeeAdjustments" type="{}ItemFeeAdjustmentsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdjustedItemType", propOrder = {
    "amazonOrderItemCode",
    "merchantAdjustmentItemID",
    "sku",
    "itemPriceAdjustments",
    "itemFeeAdjustments"
})
public class AdjustedItemType {

    @XmlElement(name = "AmazonOrderItemCode")
    protected long amazonOrderItemCode;
    @XmlElement(name = "MerchantAdjustmentItemID")
    protected long merchantAdjustmentItemID;
    @XmlElement(name = "SKU", required = true)
    protected String sku;
    @XmlElement(name = "ItemPriceAdjustments", required = true)
    protected ItemPriceAdjustmentsType itemPriceAdjustments;
    @XmlElement(name = "ItemFeeAdjustments", required = true)
    protected ItemFeeAdjustmentsType itemFeeAdjustments;

    /**
     * Gets the value of the amazonOrderItemCode property.
     * 
     */
    public long getAmazonOrderItemCode() {
        return amazonOrderItemCode;
    }

    /**
     * Sets the value of the amazonOrderItemCode property.
     * 
     */
    public void setAmazonOrderItemCode(long value) {
        this.amazonOrderItemCode = value;
    }

    /**
     * Gets the value of the merchantAdjustmentItemID property.
     * 
     */
    public long getMerchantAdjustmentItemID() {
        return merchantAdjustmentItemID;
    }

    /**
     * Sets the value of the merchantAdjustmentItemID property.
     * 
     */
    public void setMerchantAdjustmentItemID(long value) {
        this.merchantAdjustmentItemID = value;
    }

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKU() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKU(String value) {
        this.sku = value;
    }

    /**
     * Gets the value of the itemPriceAdjustments property.
     * 
     * @return
     *     possible object is
     *     {@link ItemPriceAdjustmentsType }
     *     
     */
    public ItemPriceAdjustmentsType getItemPriceAdjustments() {
        return itemPriceAdjustments;
    }

    /**
     * Sets the value of the itemPriceAdjustments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemPriceAdjustmentsType }
     *     
     */
    public void setItemPriceAdjustments(ItemPriceAdjustmentsType value) {
        this.itemPriceAdjustments = value;
    }

    /**
     * Gets the value of the itemFeeAdjustments property.
     * 
     * @return
     *     possible object is
     *     {@link ItemFeeAdjustmentsType }
     *     
     */
    public ItemFeeAdjustmentsType getItemFeeAdjustments() {
        return itemFeeAdjustments;
    }

    /**
     * Sets the value of the itemFeeAdjustments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemFeeAdjustmentsType }
     *     
     */
    public void setItemFeeAdjustments(ItemFeeAdjustmentsType value) {
        this.itemFeeAdjustments = value;
    }

}
