//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.01 at 12:53:15 AM PHT 
//


package com.elcuk.mws.jaxb.payments;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for FulfillmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FulfillmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MerchantFulfillmentID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PostedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Item" type="{}ItemType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AdjustedItem" type="{}AdjustedItemType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FulfillmentType", propOrder = {
    "merchantFulfillmentID",
    "postedDate",
    "item",
    "adjustedItem"
})
public class FulfillmentType {

    @XmlElement(name = "MerchantFulfillmentID", required = true)
    protected String merchantFulfillmentID;
    @XmlElement(name = "PostedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar postedDate;
    @XmlElement(name = "Item")
    protected List<ItemType> item;
    @XmlElement(name = "AdjustedItem")
    protected AdjustedItemType adjustedItem;

    /**
     * Gets the value of the merchantFulfillmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantFulfillmentID() {
        return merchantFulfillmentID;
    }

    /**
     * Sets the value of the merchantFulfillmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantFulfillmentID(String value) {
        this.merchantFulfillmentID = value;
    }

    /**
     * Gets the value of the postedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPostedDate() {
        return postedDate;
    }

    /**
     * Sets the value of the postedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPostedDate(XMLGregorianCalendar value) {
        this.postedDate = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemType }
     * 
     * 
     */
    public List<ItemType> getItem() {
        if (item == null) {
            item = new ArrayList<ItemType>();
        }
        return this.item;
    }

    /**
     * Gets the value of the adjustedItem property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustedItemType }
     *     
     */
    public AdjustedItemType getAdjustedItem() {
        return adjustedItem;
    }

    /**
     * Sets the value of the adjustedItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustedItemType }
     *     
     */
    public void setAdjustedItem(AdjustedItemType value) {
        this.adjustedItem = value;
    }

}
