//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.01 at 12:53:15 AM PHT 
//


package com.elcuk.mws.jaxb.payments;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AmazonOrderItemCode" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="ItemPrice" type="{}ItemPriceType"/>
 *         &lt;element name="ItemFees" type="{}ItemFeesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemType", propOrder = {
    "amazonOrderItemCode",
    "sku",
    "quantity",
    "itemPrice",
    "itemFees"
})
public class ItemType {

    @XmlElement(name = "AmazonOrderItemCode")
    protected long amazonOrderItemCode;
    @XmlElement(name = "SKU", required = true)
    protected String sku;
    @XmlElement(name = "Quantity")
    protected byte quantity;
    @XmlElement(name = "ItemPrice", required = true)
    protected ItemPriceType itemPrice;
    @XmlElement(name = "ItemFees", required = true)
    protected ItemFeesType itemFees;

    /**
     * Gets the value of the amazonOrderItemCode property.
     * 
     */
    public long getAmazonOrderItemCode() {
        return amazonOrderItemCode;
    }

    /**
     * Sets the value of the amazonOrderItemCode property.
     * 
     */
    public void setAmazonOrderItemCode(long value) {
        this.amazonOrderItemCode = value;
    }

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKU() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKU(String value) {
        this.sku = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public byte getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(byte value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the itemPrice property.
     * 
     * @return
     *     possible object is
     *     {@link ItemPriceType }
     *     
     */
    public ItemPriceType getItemPrice() {
        return itemPrice;
    }

    /**
     * Sets the value of the itemPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemPriceType }
     *     
     */
    public void setItemPrice(ItemPriceType value) {
        this.itemPrice = value;
    }

    /**
     * Gets the value of the itemFees property.
     * 
     * @return
     *     possible object is
     *     {@link ItemFeesType }
     *     
     */
    public ItemFeesType getItemFees() {
        return itemFees;
    }

    /**
     * Sets the value of the itemFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemFeesType }
     *     
     */
    public void setItemFees(ItemFeesType value) {
        this.itemFees = value;
    }

}
