//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.01 at 12:53:15 AM PHT 
//


package com.elcuk.mws.jaxb.payments;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="SettlementReport" type="{}SettlementReportType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageType", propOrder = {
    "messageID",
    "settlementReport"
})
public class MessageType {

    @XmlElement(name = "MessageID")
    protected byte messageID;
    @XmlElement(name = "SettlementReport", required = true)
    protected SettlementReportType settlementReport;

    /**
     * Gets the value of the messageID property.
     * 
     */
    public byte getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     */
    public void setMessageID(byte value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the settlementReport property.
     * 
     * @return
     *     possible object is
     *     {@link SettlementReportType }
     *     
     */
    public SettlementReportType getSettlementReport() {
        return settlementReport;
    }

    /**
     * Sets the value of the settlementReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlementReportType }
     *     
     */
    public void setSettlementReport(SettlementReportType value) {
        this.settlementReport = value;
    }

}
