//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.01 at 12:53:15 AM PHT 
//


package com.elcuk.mws.jaxb.payments;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.elcuk.mws.jaxb.payments package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AmazonEnvelope_QNAME = new QName("", "AmazonEnvelope");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.elcuk.mws.jaxb.payments
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdjustedItemType }
     * 
     */
    public AdjustedItemType createAdjustedItemType() {
        return new AdjustedItemType();
    }

    /**
     * Create an instance of {@link FulfillmentType }
     * 
     */
    public FulfillmentType createFulfillmentType() {
        return new FulfillmentType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link AdjustmentType }
     * 
     */
    public AdjustmentType createAdjustmentType() {
        return new AdjustmentType();
    }

    /**
     * Create an instance of {@link TotalAmountType }
     * 
     */
    public TotalAmountType createTotalAmountType() {
        return new TotalAmountType();
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link ItemPriceType }
     * 
     */
    public ItemPriceType createItemPriceType() {
        return new ItemPriceType();
    }

    /**
     * Create an instance of {@link FeeType }
     * 
     */
    public FeeType createFeeType() {
        return new FeeType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link ItemFeeAdjustmentsType }
     * 
     */
    public ItemFeeAdjustmentsType createItemFeeAdjustmentsType() {
        return new ItemFeeAdjustmentsType();
    }

    /**
     * Create an instance of {@link SettlementReportType }
     * 
     */
    public SettlementReportType createSettlementReportType() {
        return new SettlementReportType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link ItemPriceAdjustmentsType }
     * 
     */
    public ItemPriceAdjustmentsType createItemPriceAdjustmentsType() {
        return new ItemPriceAdjustmentsType();
    }

    /**
     * Create an instance of {@link OtherTransactionType }
     * 
     */
    public OtherTransactionType createOtherTransactionType() {
        return new OtherTransactionType();
    }

    /**
     * Create an instance of {@link ItemFeesType }
     * 
     */
    public ItemFeesType createItemFeesType() {
        return new ItemFeesType();
    }

    /**
     * Create an instance of {@link SettlementDataType }
     * 
     */
    public SettlementDataType createSettlementDataType() {
        return new SettlementDataType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link AmazonEnvelopeType }
     * 
     */
    public AmazonEnvelopeType createAmazonEnvelopeType() {
        return new AmazonEnvelopeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmazonEnvelopeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AmazonEnvelope")
    public JAXBElement<AmazonEnvelopeType> createAmazonEnvelope(AmazonEnvelopeType value) {
        return new JAXBElement<AmazonEnvelopeType>(_AmazonEnvelope_QNAME, AmazonEnvelopeType.class, null, value);
    }

}
