//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.01 at 12:53:15 AM PHT 
//


package com.elcuk.mws.jaxb.payments;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SettlementReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SettlementReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SettlementData" type="{}SettlementDataType"/>
 *         &lt;element name="Order" type="{}OrderType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Adjustment" type="{}AdjustmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OtherTransaction" type="{}OtherTransactionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SettlementReportType", propOrder = {
    "settlementData",
    "order",
    "adjustment",
    "otherTransaction"
})
public class SettlementReportType {

    @XmlElement(name = "SettlementData", required = true)
    protected SettlementDataType settlementData;
    @XmlElement(name = "Order")
    protected List<OrderType> order;
    @XmlElement(name = "Adjustment")
    protected List<AdjustmentType> adjustment;
    @XmlElement(name = "OtherTransaction", required = true)
    protected OtherTransactionType otherTransaction;

    /**
     * Gets the value of the settlementData property.
     * 
     * @return
     *     possible object is
     *     {@link SettlementDataType }
     *     
     */
    public SettlementDataType getSettlementData() {
        return settlementData;
    }

    /**
     * Sets the value of the settlementData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlementDataType }
     *     
     */
    public void setSettlementData(SettlementDataType value) {
        this.settlementData = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the order property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderType }
     * 
     * 
     */
    public List<OrderType> getOrder() {
        if (order == null) {
            order = new ArrayList<OrderType>();
        }
        return this.order;
    }

    /**
     * Gets the value of the adjustment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adjustment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjustment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdjustmentType }
     * 
     * 
     */
    public List<AdjustmentType> getAdjustment() {
        if (adjustment == null) {
            adjustment = new ArrayList<AdjustmentType>();
        }
        return this.adjustment;
    }

    /**
     * Gets the value of the otherTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link OtherTransactionType }
     *     
     */
    public OtherTransactionType getOtherTransaction() {
        return otherTransaction;
    }

    /**
     * Sets the value of the otherTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherTransactionType }
     *     
     */
    public void setOtherTransaction(OtherTransactionType value) {
        this.otherTransaction = value;
    }

}
